import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { PatientContext } from "./Components/PatientContext";
import { DoctorContext } from "./Components/DoctorContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PatientContext>
          <DoctorContext>{children}</DoctorContext>
        </PatientContext>
      </body>
    </html>
  );
}
